test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,9 +20,19 @@ jobs:
           git diff --name-only --exit-code
       - run: |
           node dist/index.js
+
+          if ! [ -x "$(command -v kotlinc)" ]; then
+            echo 'Error: Expected kotlinc to be installed.' >&2
+            exit 1
+          fi
+
+          if [ -x "$(command -v kotlinc-native)" ]; then
+            echo 'Error: Expected kotlinc-native NOT to be installed.' >&2
+            exit 1
+          fi
         env:
           INPUT_VERSION: 1.4.21
-          INPUT_install-native: false
+          INPUT_INSTALL-NATIVE: false
 
   test:
     runs-on: ${{ matrix.os }}
